### ISSUE TITLE
Final formatting checklist

### ISSUE THREAD

**Issue by trvrb** [blab/mers-structure#15]
Feel free to edit.

### For journal submission

- [x] Comment out `ulem` package: https://github.com/blab/mers-structure/blob/master/mers-structure.tex#L72. This allows commenting but makes what should be italicized text show up as underlined.
- [x] Move main text figures up a couple paragraphs so they show up closer to where they are first referenced in the main text. For example, Figure 1 is first referenced on page 3 but doesn't show up until page 5. It should be on page 4.

### Additionally for bioRxiv

- [x] Remove line numbers: https://github.com/blab/mers-structure/blob/master/mers-structure.tex#L54
